In [1]:
from mediaeval_fake_news.prepare_graphs_basic_info import get_training_dataframe
from mediaeval_fake_news.subgraph_sampling import subgraph_random_sampling
from mediaeval_fake_news.graph2vec import get_weighted_average_embeddings, get_largest_subgraph_embedding
from mediaeval_fake_news.deepwalk_utils import clean_for_deepwalk
from mediaeval_fake_news.models.rnn import Rnn
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, cross_val_predict, KFold
from sklearn.metrics import matthews_corrcoef
import numpy as np
np.random.seed(42)
import torch as th
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [2]:
dataset_path = "../datasets/mediaeval_fake_news_dataset/graphs/"
df, graph_dict, node_df = get_training_dataframe(dataset_path, two_class=False, get_node_df=True)
#node_df = node_df.set_index(['graph_id', 'node_id'])
print(graph_dict.keys()) # in this order in the df


dict_keys(['conspiracy_graphs', 'non_conspiracy_graphs', 'other_conspiracy_graphs'])


# Brainome

In [6]:
# for basic features

df.shape
df.to_csv("basic_features.csv", index=False)
# run btc -measureonly basic_features.csv -target label -ignorecolumns nodeID_list


for two class, brainome gives Best guess accuracy: 88.40%. This is just choosing 0 for everything. Got yellow. For two class, also got the same as choosing most common"

In [9]:
consp, non_consp, other_consp = graphs['conspiracy_graphs'], graphs['non_conspiracy_graphs'], graphs['other_conspiracy_graphs']
g2v1 = get_weighted_average_embeddings(consp, label=1)
g2v2 = get_weighted_average_embeddings(non_consp, label=2)
g2v3 = get_weighted_average_embeddings(other_consp, label=3)
g2v_dfs = [g2v1, g2v2, g2v3]

weighted_g2v0  weighted_g2v1  weighted_g2v2  weighted_g2v3  \
0        -0.135185      -0.048401      -0.039733       0.052115   
1        -0.166506      -0.058801      -0.061478       0.057558   
2        -0.074059      -0.031809      -0.025210       0.028706   
3        -0.096855      -0.040148      -0.038347       0.037246   
4        -0.078578      -0.033788      -0.031015       0.034652   
..             ...            ...            ...            ...   
265      -0.119380      -0.044606      -0.038471       0.041389   
266      -0.102998      -0.034455      -0.030975       0.034713   
267      -0.147454      -0.052583      -0.057560       0.056190   
268      -0.005257       0.000199       0.000832       0.001242   
269      -0.136005      -0.041924      -0.054682       0.067163   

     weighted_g2v4  weighted_g2v5  weighted_g2v6  weighted_g2v7  \
0        -0.140880       0.107147      -0.059703      -0.047766   
1        -0.184593       0.148296      -0.057601      -0.060534   
2        -0.074920       0.061906      -0.036715      -0.027512   
3        -0.092192       0.074869      -0.029323      -0.041718   
4        -0.087756       0.071091      -0.030422      -0.028083   
..             ...            ...            ...            ...   
265      -0.121399       0.099895      -0.046840      -0.043110   
266      -0.103247       0.075003      -0.038463      -0.041934   
267      -0.171025       0.146895      -0.072731      -0.048643   
268      -0.004764       0.002313      -0.001831      -0.000076   
269      -0.122318       0.098035      -0.055701      -0.051978   

     weighted_g2v8  weighted_g2v9  ...  weighted_g2v55  weighted_g2v56  \
0         0.025264       0.053888  ...        0.051684        0.111765   
1         0.020224       0.068468  ...        0.072657        0.124573   
2         0.012253       0.033411  ...        0.034663        0.066087   
3         0.010148       0.043166  ...        0.046897        0.082165   
4         0.016498       0.028220  ...        0.029060        0.067963   
..             ...            ...  ...             ...             ...   
265       0.013045       0.045818  ...        0.044321        0.091078   
266       0.014526       0.033481  ...        0.036479        0.072301   
267       0.017665       0.060857  ...        0.054055        0.116071   
268       0.000840       0.001468  ...        0.002257        0.000675   
269       0.028912       0.066033  ...        0.054393        0.104811   

     weighted_g2v57  weighted_g2v58  weighted_g2v59  weighted_g2v60  \
0         -0.000768        0.051560        0.172556       -0.056201   
1          0.001599        0.080217        0.233222       -0.069000   
2         -0.002857        0.034992        0.098433       -0.027912   
3          0.003455        0.043655        0.126909       -0.047726   
4         -0.002160        0.032116        0.111422       -0.027850   
..              ...             ...             ...             ...   
265        0.006572        0.052187        0.156923       -0.046507   
266        0.004753        0.046622        0.120859       -0.039335   
267       -0.007857        0.081087        0.213297       -0.068011   
268       -0.000042        0.001870        0.002764       -0.002260   
269       -0.007411        0.066787        0.182105       -0.058175   

     weighted_g2v61  weighted_g2v62  weighted_g2v63  label  
0         -0.206576       -0.131849       -0.032903      1  
1         -0.245228       -0.159604       -0.037272      1  
2         -0.122374       -0.080374       -0.010138      1  
3         -0.144647       -0.093099       -0.017362      1  
4         -0.119581       -0.078706       -0.010749      1  
..              ...             ...             ...    ...  
265       -0.174894       -0.109014       -0.023418      1  
266       -0.137999       -0.088078       -0.022270      1  
267       -0.221993       -0.164980       -0.022520      1  
268       -0.006081       -0.002542        

In [15]:
all_g2v_embeddings = pd.concat(g2v_dfs)
all_g2v_embeddings.to_csv("g2v_weighted.csv", index=False)

# Using only Deepwalk
#### run deepwalk --input ../for_deepwalk.edgelist --format edgelist --output OUTFILE_NAME.txt --workers 4 --seed 42 --undirected false
### Important: only run this cell if you want to make a new deepwalk embedding

In [17]:
composite_graph = clean_for_deepwalk(dataset_path, directed=True)
!deepwalk --input for_deepwalk.edgelist --format edgelist --output march20.txt --workers 4 --seed 42 --undirected false


### Nodes all have unique IDs

In [3]:
graph_dict['conspiracy_graphs'][0].nodes()

NodeView(('32115079', '449009614', '833469625', '499613745', '450210178', '182510449', '74719838'))

In [4]:
embeddings = pd.read_csv('deepwalk-master/march20.txt', names=['deepwalk' + str(i) for i in range(64)], sep=" ")
#set index (node labels) to string for consistency with NetworkX
as_string = embeddings.index.astype('string')
embeddings = embeddings.set_index(as_string)
embeddings.head(3)

deepwalk0  deepwalk1  deepwalk2  deepwalk3  deepwalk4  deepwalk5  \
127166025   0.327048  -0.175018   0.224296  -0.304788  -0.222251   0.535962   
61721125    0.514014  -0.111906  -0.504094   0.304461   0.119720   0.193295   
127471447   0.320193   0.299958   0.126426  -0.828930   0.136684   0.066215   

           deepwalk6  deepwalk7  deepwalk8  deepwalk9  ...  deepwalk54  \
127166025  -0.267580   0.059097   0.178404  -0.844267  ...   -0.244400   
61721125   -0.145294  -0.607624   0.072884   0.312199  ...    0.537953   
127471447   0.340867  -1.203018  -0.158095   0.751009  ...    0.306866   

           deepwalk55  deepwalk56  deepwalk57  deepwalk58  deepwalk59  \
127166025   -0.030048   -0.119165    0.218429   -0.567515    0.166872   
61721125    -0.267592   -0.209925    0.365644   -0.741665   -0.070278   
127471447   -0.620950    1.211668   -0.151608   -0.585739   -0.606053   

           deepwalk60  deepwalk61  deepwalk62  deepwalk63  
127166025   -0.065369   -0.233754   -0.055578    0.034475  
61721125     0.025231   -0.253768    0.119094    0.541069  
127471447    0.755599   -0.407707    0.263721   -0.653597  

[3 rows x 64 columns]

### Trying out different Recurrent Architectures
#### First, we need to create our dataset and dataloader

In [ ]:
from mediaeval_fake_news.dataset_wrapper import GraphDataset, x_transform, y_transform
dataset = GraphDataset(df, embeddings, node_df, x_transform, y_transform)
train, valid = random_split(dataset, [1861, 466], generator=th.Generator().manual_seed(42))

# need to keep batch_size=1 because of the way the RNN part is set up.
train_dataloader = DataLoader(train, batch_size=1, shuffle=True)
valid_dataloader = DataLoader(valid, batch_size=1, shuffle=True)

#### Next, we create our RNN Model

In [127]:
device = th.device("cuda" if th.cuda.is_available() else "cpu")

sample_x, sample_y = dataset.__getitem__(0)
input_size = sample_x.shape[1]
output_size = dataset.num_classes()
model = Rnn(input_size=input_size, hidden_size=32, output_size=output_size)
model.to(device, dtype=th.float32);

#### We choose an optimizer and loss function.
#### Define any training related constants here

In [128]:
LR = 1e-4
EPOCHS=1
criterion = th.nn.CrossEntropyLoss()
optimizer = th.optim.Adam(model.parameters(), lr = LR)

#### We define a loop for training our model

In [129]:
for epoch in range(EPOCHS):
    epoch_loss = 0
    for i, (train_x, train_y) in enumerate(train_dataloader):

        optimizer.zero_grad()
        out = model.forward(train_x).unsqueeze(0)

        loss = criterion(out, train_y)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

        if i % 100 == 0:
            print(F"Iteration {i}. Loss is {epoch_loss}")
            # print(out)
            # print(train_y)
            # print(loss)
            # print()

Iteration 0. Loss is 0.5966570377349854
tensor([[-0.3855, -0.7290,  0.3539]], grad_fn=<UnsqueezeBackward0>)
tensor([2])
tensor(0.5967, grad_fn=<NllLossBackward>)
Iteration 10. Loss is 7.537882208824158
tensor([[-0.4184, -0.7532,  0.3833]], grad_fn=<UnsqueezeBackward0>)
tensor([2])
tensor(0.5707, grad_fn=<NllLossBackward>)
Iteration 20. Loss is 16.44843155145645
tensor([[-0.4298, -0.7633,  0.3973]], grad_fn=<UnsqueezeBackward0>)
tensor([2])
tensor(0.5600, grad_fn=<NllLossBackward>)
Iteration 30. Loss is 24.85945165157318
tensor([[-0.4391, -0.7721,  0.4096]], grad_fn=<UnsqueezeBackward0>)
tensor([2])
tensor(0.5509, grad_fn=<NllLossBackward>)
Iteration 40. Loss is 36.337219417095184
tensor([[-0.4506, -0.7682,  0.4150]], grad_fn=<UnsqueezeBackward0>)
tensor([0])
tensor(1.4121, grad_fn=<NllLossBackward>)
Iteration 50. Loss is 45.823095083236694
tensor([[-0.4533, -0.7616,  0.4118]], grad_fn=<UnsqueezeBackward0>)
tensor([0])
tensor(1.4134, grad_fn=<NllLossBackward>)
Iteration 60. Loss is 54.2

KeyboardInterrupt: 

### Validation Loop

In [147]:
preds = []
actuals = []
for i, (valid_x, valid_y) in enumerate(train_dataloader):
    out = model.forward(train_x).unsqueeze(0)
    pred = th.argmax(out).item()
    actual = valid_y.item()
    
    preds.append(pred)
    actuals.append(actual)
    
accuracy = sum([preds[i] == actuals[i] for i in range(len(actuals))]) / len(preds)
accuracy

0.7130574959699086

In [152]:
sum([i == 2 for i in actuals]) / len(actuals)

0.7130574959699086

In [ ]:
#TODO: this is underfitting - just predicting 1 for everything. I think. Maybe try to 

## using a basic logistic regression model to test what works

In [19]:
dw_feats = df[['label', 'nodeID_list']]
def get_deepwalk_mean(row):
    graph_nodes = row['nodeID_list']
    node_embed = embeddings[[(node in graph_nodes) for node in embeddings.index]]
    avg_embed = node_embed.mean(axis=0)
    return avg_embed

dw_feats[['dw_mean'+str(i) for i in range(64)]] = dw_feats.apply(get_deepwalk_mean, axis=1)
dw_feats.head(3)

KeyboardInterrupt: 

In [15]:
# get data first
dw_feats = dw_feats.drop('nodeID_list', axis=1)
X, y = np.array(dw_feats.drop('label', axis=1)), np.ravel(dw_feats[['label']])
kf = KFold(n_splits=5, random_state=42, shuffle=True)


In [16]:
scores = []
for train_idx, val_idx in kf.split(X):
    X_train, y_train = X[train_idx], y[train_idx]
    X_val, y_val = X[val_idx], y[val_idx]
    model = LogisticRegression(random_state=42, class_weight='balanced', C=.0001)
    from sklearn import svm
    model = svm.SVC(kernel='rbf', class_weight="balanced", C=5)
    model.fit(X_train, y_train)
    preds = model.predict(X_val)
    score = matthews_corrcoef(y_val, preds)
    #print(preds)
    scores.append(score)
scores

[0.33811562230497183,
 0.4170142973854589,
 0.36276128940856917,
 0.3848279938846305,
 0.3644198947839967]